import React from 'react';

interface TermsAndConditionsProps {
  onBack: () => void;
}

export default function TermsAndConditions({ onBack }: TermsAndConditionsProps) {
  return (
    <div className="legal-page">
      <div className="legal-header">
        <button className="legal-back-btn" onClick={onBack}>
          ← Back
        </button>
        <h1>Terms & Conditions</h1>
        <p className="legal-updated">Last updated: September 2026</p>
      </div>

      <div className="legal-content">
        <section className="legal-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the AI Study Assistant ("the Service"), you agree to be bound by
            these Terms and Conditions. If you do not agree with any part of these terms, you may not
            use the Service.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Description of Service</h2>
          <p>
            AI Study Assistant is an AI-powered learning tool that allows you to upload documents and photos
            (including PDFs, images, Word documents, and text) and generate study materials including summaries,
            quizzes, and flashcards using Google's Gemini AI. The Service also provides a conversational AI
            interface for asking questions about your uploaded materials.
          </p>
        </section>

        <section className="legal-section">
          <h2>3. User Accounts</h2>
          <p>
            To use the Service, you must sign in using your Google account. You are responsible for
            maintaining the security of your account and for all activities that occur under your
            account. You agree to:
          </p>
          <ul>
            <li>Provide accurate and complete information during registration</li>
            <li>Keep your account credentials secure</li>
            <li>Notify us immediately of any unauthorized use of your account</li>
            <li>Accept responsibility for all activities under your account</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>4. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Upload or process content that is illegal, harmful, or infringes on others' rights</li>
            <li>Attempt to reverse-engineer, decompile, or disassemble the Service</li>
            <li>Interfere with or disrupt the Service's infrastructure</li>
            <li>Attempt to access other users' data or accounts</li>
            <li>Use the Service for any commercial purpose without prior written consent</li>
            <li>Upload malicious files or content designed to exploit the system</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>5. Intellectual Property</h2>
          <h3>Your Content</h3>
          <p>
            You retain full ownership of all documents, photos, and materials you upload and all content you create using
            the Service. We do not claim any ownership over your uploaded materials or generated study
            content.
          </p>
          <h3>Our Service</h3>
          <p>
            The AI Study Assistant application, including its design, code, and branding, is protected
            by intellectual property laws. You may not copy, modify, or distribute any part of the
            Service without permission.
          </p>
        </section>

        <section className="legal-section">
          <h2>6. AI-Generated Content</h2>
          <p>
            The summaries, quizzes, flashcards, and answers generated by the AI are provided for
            educational purposes only. While we strive for accuracy, AI-generated content may contain
            errors or inaccuracies. You should:
          </p>
          <ul>
            <li>Verify important information from authoritative sources</li>
            <li>Not rely solely on AI-generated content for critical academic decisions</li>
            <li>Use AI-generated materials as supplementary study aids</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>7. Data and Privacy</h2>
          <p>
            Your use of the Service is also governed by our Privacy Policy, which describes how we
            collect, use, and protect your information. By using the Service, you consent to the
            practices described in the Privacy Policy.
          </p>
        </section>

        <section className="legal-section">
          <h2>8. Service Availability</h2>
          <p>
            We strive to maintain high availability of the Service but do not guarantee uninterrupted
            access. The Service may be temporarily unavailable due to:
          </p>
          <ul>
            <li>Scheduled maintenance and updates</li>
            <li>Third-party service outages (Google, Supabase, Vercel)</li>
            <li>Unforeseen technical issues</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, AI Study Assistant and its creators shall not be
            liable for any indirect, incidental, special, consequential, or punitive damages resulting
            from your use of or inability to use the Service, including but not limited to:
          </p>
          <ul>
            <li>Loss of data or study materials</li>
            <li>Inaccurate AI-generated content</li>
            <li>Unauthorized access to your account</li>
            <li>Service interruptions or downtime</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>10. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the Service at any time,
            with or without cause, with or without notice. You may also terminate your account at any
            time by contacting us. Upon termination, your data will be deleted in accordance with our
            Privacy Policy.
          </p>
        </section>

        <section className="legal-section">
          <h2>11. Modifications to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will notify users of
            significant changes by updating the "Last updated" date. Your continued use of the
            Service after changes constitutes acceptance of the modified Terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>12. Contact</h2>
          <p>
            If you have any questions about these Terms, please reach out through our application's
            support channels.
          </p>
        </section>
      </div>
    </div>
  );
}
